/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as NewsRouteImport } from './routes/news'
import { Route as ExpertisesRouteImport } from './routes/expertises'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CarteDeVisiteRouteImport } from './routes/carte-de-visite'
import { Route as CarteRouteImport } from './routes/carte'
import { Route as CabinetRouteImport } from './routes/cabinet'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ActualitesRouteImport } from './routes/actualites'
import { Route as R403RouteImport } from './routes/403'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewsIdRouteImport } from './routes/news_.$id'
import { Route as ExpertisesSlugRouteImport } from './routes/expertises_.$slug'
import { Route as CabinetCarteRouteImport } from './routes/cabinet.carte'
import { Route as ActualitesIdRouteImport } from './routes/actualites_.$id'
import { Route as ExpertisesSlugFaqRouteImport } from './routes/expertises_.$slug.faq'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertisesRoute = ExpertisesRouteImport.update({
  id: '/expertises',
  path: '/expertises',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CarteDeVisiteRoute = CarteDeVisiteRouteImport.update({
  id: '/carte-de-visite',
  path: '/carte-de-visite',
  getParentRoute: () => rootRouteImport,
} as any)
const CarteRoute = CarteRouteImport.update({
  id: '/carte',
  path: '/carte',
  getParentRoute: () => rootRouteImport,
} as any)
const CabinetRoute = CabinetRouteImport.update({
  id: '/cabinet',
  path: '/cabinet',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ActualitesRoute = ActualitesRouteImport.update({
  id: '/actualites',
  path: '/actualites',
  getParentRoute: () => rootRouteImport,
} as any)
const R403Route = R403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIdRoute = NewsIdRouteImport.update({
  id: '/news_/$id',
  path: '/news/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertisesSlugRoute = ExpertisesSlugRouteImport.update({
  id: '/expertises_/$slug',
  path: '/expertises/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CabinetCarteRoute = CabinetCarteRouteImport.update({
  id: '/carte',
  path: '/carte',
  getParentRoute: () => CabinetRoute,
} as any)
const ActualitesIdRoute = ActualitesIdRouteImport.update({
  id: '/actualites_/$id',
  path: '/actualites/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertisesSlugFaqRoute = ExpertisesSlugFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => ExpertisesSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/403': typeof R403Route
  '/actualites': typeof ActualitesRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cabinet': typeof CabinetRouteWithChildren
  '/carte': typeof CarteRoute
  '/carte-de-visite': typeof CarteDeVisiteRoute
  '/contact': typeof ContactRoute
  '/equipe': typeof EquipeRoute
  '/expertises': typeof ExpertisesRoute
  '/news': typeof NewsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/team': typeof TeamRoute
  '/actualites/$id': typeof ActualitesIdRoute
  '/cabinet/carte': typeof CabinetCarteRoute
  '/expertises/$slug': typeof ExpertisesSlugRouteWithChildren
  '/news/$id': typeof NewsIdRoute
  '/expertises/$slug/faq': typeof ExpertisesSlugFaqRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/403': typeof R403Route
  '/actualites': typeof ActualitesRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cabinet': typeof CabinetRouteWithChildren
  '/carte': typeof CarteRoute
  '/carte-de-visite': typeof CarteDeVisiteRoute
  '/contact': typeof ContactRoute
  '/equipe': typeof EquipeRoute
  '/expertises': typeof ExpertisesRoute
  '/news': typeof NewsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/team': typeof TeamRoute
  '/actualites/$id': typeof ActualitesIdRoute
  '/cabinet/carte': typeof CabinetCarteRoute
  '/expertises/$slug': typeof ExpertisesSlugRouteWithChildren
  '/news/$id': typeof NewsIdRoute
  '/expertises/$slug/faq': typeof ExpertisesSlugFaqRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/403': typeof R403Route
  '/actualites': typeof ActualitesRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cabinet': typeof CabinetRouteWithChildren
  '/carte': typeof CarteRoute
  '/carte-de-visite': typeof CarteDeVisiteRoute
  '/contact': typeof ContactRoute
  '/equipe': typeof EquipeRoute
  '/expertises': typeof ExpertisesRoute
  '/news': typeof NewsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/team': typeof TeamRoute
  '/actualites_/$id': typeof ActualitesIdRoute
  '/cabinet/carte': typeof CabinetCarteRoute
  '/expertises_/$slug': typeof ExpertisesSlugRouteWithChildren
  '/news_/$id': typeof NewsIdRoute
  '/expertises_/$slug/faq': typeof ExpertisesSlugFaqRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/403'
    | '/actualites'
    | '/admin'
    | '/auth'
    | '/cabinet'
    | '/carte'
    | '/carte-de-visite'
    | '/contact'
    | '/equipe'
    | '/expertises'
    | '/news'
    | '/reset-password'
    | '/team'
    | '/actualites/$id'
    | '/cabinet/carte'
    | '/expertises/$slug'
    | '/news/$id'
    | '/expertises/$slug/faq'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/403'
    | '/actualites'
    | '/admin'
    | '/auth'
    | '/cabinet'
    | '/carte'
    | '/carte-de-visite'
    | '/contact'
    | '/equipe'
    | '/expertises'
    | '/news'
    | '/reset-password'
    | '/team'
    | '/actualites/$id'
    | '/cabinet/carte'
    | '/expertises/$slug'
    | '/news/$id'
    | '/expertises/$slug/faq'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/403'
    | '/actualites'
    | '/admin'
    | '/auth'
    | '/cabinet'
    | '/carte'
    | '/carte-de-visite'
    | '/contact'
    | '/equipe'
    | '/expertises'
    | '/news'
    | '/reset-password'
    | '/team'
    | '/actualites_/$id'
    | '/cabinet/carte'
    | '/expertises_/$slug'
    | '/news_/$id'
    | '/expertises_/$slug/faq'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  R403Route: typeof R403Route
  ActualitesRoute: typeof ActualitesRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CabinetRoute: typeof CabinetRouteWithChildren
  CarteRoute: typeof CarteRoute
  CarteDeVisiteRoute: typeof CarteDeVisiteRoute
  ContactRoute: typeof ContactRoute
  EquipeRoute: typeof EquipeRoute
  ExpertisesRoute: typeof ExpertisesRoute
  NewsRoute: typeof NewsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TeamRoute: typeof TeamRoute
  ActualitesIdRoute: typeof ActualitesIdRoute
  ExpertisesSlugRoute: typeof ExpertisesSlugRouteWithChildren
  NewsIdRoute: typeof NewsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expertises': {
      id: '/expertises'
      path: '/expertises'
      fullPath: '/expertises'
      preLoaderRoute: typeof ExpertisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carte-de-visite': {
      id: '/carte-de-visite'
      path: '/carte-de-visite'
      fullPath: '/carte-de-visite'
      preLoaderRoute: typeof CarteDeVisiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carte': {
      id: '/carte'
      path: '/carte'
      fullPath: '/carte'
      preLoaderRoute: typeof CarteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cabinet': {
      id: '/cabinet'
      path: '/cabinet'
      fullPath: '/cabinet'
      preLoaderRoute: typeof CabinetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actualites': {
      id: '/actualites'
      path: '/actualites'
      fullPath: '/actualites'
      preLoaderRoute: typeof ActualitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news_/$id': {
      id: '/news_/$id'
      path: '/news/$id'
      fullPath: '/news/$id'
      preLoaderRoute: typeof NewsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expertises_/$slug': {
      id: '/expertises_/$slug'
      path: '/expertises/$slug'
      fullPath: '/expertises/$slug'
      preLoaderRoute: typeof ExpertisesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cabinet/carte': {
      id: '/cabinet/carte'
      path: '/carte'
      fullPath: '/cabinet/carte'
      preLoaderRoute: typeof CabinetCarteRouteImport
      parentRoute: typeof CabinetRoute
    }
    '/actualites_/$id': {
      id: '/actualites_/$id'
      path: '/actualites/$id'
      fullPath: '/actualites/$id'
      preLoaderRoute: typeof ActualitesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expertises_/$slug/faq': {
      id: '/expertises_/$slug/faq'
      path: '/faq'
      fullPath: '/expertises/$slug/faq'
      preLoaderRoute: typeof ExpertisesSlugFaqRouteImport
      parentRoute: typeof ExpertisesSlugRoute
    }
  }
}

interface CabinetRouteChildren {
  CabinetCarteRoute: typeof CabinetCarteRoute
}

const CabinetRouteChildren: CabinetRouteChildren = {
  CabinetCarteRoute: CabinetCarteRoute,
}

const CabinetRouteWithChildren =
  CabinetRoute._addFileChildren(CabinetRouteChildren)

interface ExpertisesSlugRouteChildren {
  ExpertisesSlugFaqRoute: typeof ExpertisesSlugFaqRoute
}

const ExpertisesSlugRouteChildren: ExpertisesSlugRouteChildren = {
  ExpertisesSlugFaqRoute: ExpertisesSlugFaqRoute,
}

const ExpertisesSlugRouteWithChildren = ExpertisesSlugRoute._addFileChildren(
  ExpertisesSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  R403Route: R403Route,
  ActualitesRoute: ActualitesRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CabinetRoute: CabinetRouteWithChildren,
  CarteRoute: CarteRoute,
  CarteDeVisiteRoute: CarteDeVisiteRoute,
  ContactRoute: ContactRoute,
  EquipeRoute: EquipeRoute,
  ExpertisesRoute: ExpertisesRoute,
  NewsRoute: NewsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TeamRoute: TeamRoute,
  ActualitesIdRoute: ActualitesIdRoute,
  ExpertisesSlugRoute: ExpertisesSlugRouteWithChildren,
  NewsIdRoute: NewsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
