
CREATE TABLE public.landing_pages (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  slug text NOT NULL UNIQUE,
  city text NOT NULL DEFAULT '',
  country text NOT NULL DEFAULT '',
  country_code text NOT NULL DEFAULT 'FR',
  expertise_slug text,
  title_fr text NOT NULL DEFAULT '',
  title_en text NOT NULL DEFAULT '',
  meta_description_fr text NOT NULL DEFAULT '',
  meta_description_en text NOT NULL DEFAULT '',
  h1_fr text NOT NULL DEFAULT '',
  h1_en text NOT NULL DEFAULT '',
  intro_fr text NOT NULL DEFAULT '',
  intro_en text NOT NULL DEFAULT '',
  content_fr text NOT NULL DEFAULT '',
  content_en text NOT NULL DEFAULT '',
  image_url text,
  published boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.landing_pages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Published landing pages readable by everyone"
  ON public.landing_pages FOR SELECT
  USING (published = true OR is_staff(auth.uid()));

CREATE POLICY "Staff manage landing pages"
  ON public.landing_pages FOR ALL TO authenticated
  USING (is_staff(auth.uid())) WITH CHECK (is_staff(auth.uid()));

CREATE TRIGGER set_landing_pages_updated_at
  BEFORE UPDATE ON public.landing_pages
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE INDEX idx_landing_pages_slug ON public.landing_pages(slug);
CREATE INDEX idx_landing_pages_published ON public.landing_pages(published, sort_order);

-- Seed 12 geo-targeted pages
INSERT INTO public.landing_pages (slug, city, country, country_code, expertise_slug, title_fr, title_en, meta_description_fr, meta_description_en, h1_fr, h1_en, intro_fr, intro_en, content_fr, content_en, sort_order) VALUES

('avocat-droit-affaires-paris', 'Paris', 'France', 'FR', 'droit-des-affaires',
 'Avocat Droit des Affaires à Paris | Cabinet Manuela DIABATE',
 'Business Law Attorney in Paris | Manuela DIABATE Law Firm',
 'Avocat en droit des affaires à Paris : conseil aux entreprises, M&A, contrats, contentieux commercial. Cabinet Manuela DIABATE, expertise franco-africaine.',
 'Business law attorney in Paris: corporate advisory, M&A, contracts, commercial litigation. Manuela DIABATE, French-African expertise.',
 'Avocat en droit des affaires à Paris',
 'Business Law Attorney in Paris',
 'Le Cabinet Manuela DIABATE accompagne entreprises françaises et internationales à Paris en droit des affaires : structuration, opérations de croissance, contrats stratégiques et résolution des litiges commerciaux.',
 'Manuela DIABATE Law Firm assists French and international companies in Paris with business law: structuring, growth operations, strategic contracts and commercial dispute resolution.',
 E'## Nos services en droit des affaires à Paris\n\n- Conseil et structuration juridique des sociétés\n- Fusions-acquisitions (M&A) et opérations de capital\n- Négociation et rédaction de contrats commerciaux\n- Pactes d''associés, gouvernance, restructuration\n- Contentieux commercial et arbitrage\n\n## Pourquoi un avocat d''affaires à Paris ?\n\nParis reste la première place économique francophone. Notre cabinet, situé au cœur du 17e arrondissement, conseille PME, ETI et groupes internationaux sur leurs opérations en France et leur expansion vers l''Afrique francophone (zone OHADA).\n\n## Une expertise franco-africaine unique\n\nNous combinons une parfaite maîtrise du droit français avec une connaissance approfondie du droit OHADA et de la pratique des affaires en Côte d''Ivoire. Idéal pour les groupes opérant entre la France et l''Afrique de l''Ouest.',
 E'## Our business law services in Paris\n\n- Corporate structuring and advisory\n- Mergers and acquisitions (M&A)\n- Commercial contract drafting and negotiation\n- Shareholders agreements, governance, restructuring\n- Commercial litigation and arbitration\n\n## Why a business attorney in Paris?\n\nParis remains the leading francophone economic hub. Our firm, located in the heart of the 17th district, advises SMEs and international groups on their operations in France and expansion into French-speaking Africa (OHADA zone).\n\n## A unique French-African expertise\n\nWe combine deep mastery of French law with extensive knowledge of OHADA law and business practice in Côte d''Ivoire — ideal for groups operating between France and West Africa.',
 1),

('avocat-droit-affaires-abidjan', 'Abidjan', 'Côte d''Ivoire', 'CI', 'droit-des-affaires',
 'Avocat Droit des Affaires à Abidjan | Cabinet Manuela DIABATE',
 'Business Law Attorney in Abidjan | Manuela DIABATE Law Firm',
 'Avocat en droit des affaires à Abidjan : OHADA, M&A, contrats, contentieux. Cabinet international franco-ivoirien Manuela DIABATE.',
 'Business law attorney in Abidjan: OHADA, M&A, contracts, litigation. International French-Ivorian firm Manuela DIABATE.',
 'Avocat en droit des affaires à Abidjan',
 'Business Law Attorney in Abidjan',
 'Conseil juridique aux entreprises à Abidjan : implantation en Côte d''Ivoire, droit OHADA, opérations transfrontalières France-Afrique.',
 'Legal counsel for companies in Abidjan: setup in Côte d''Ivoire, OHADA law, France-Africa cross-border operations.',
 E'## Services pour entreprises à Abidjan\n\n- Création et structuration de sociétés en Côte d''Ivoire (SA, SARL, SAS OHADA)\n- Conformité OHADA et droit ivoirien\n- M&A et joint-ventures\n- Contrats commerciaux et distribution\n- Contentieux et arbitrage CCJA\n\n## Abidjan, hub économique de l''Afrique de l''Ouest\n\nAbidjan concentre les sièges régionaux des groupes internationaux opérant en zone UEMOA. Notre expertise franco-ivoirienne facilite vos investissements et opérations.',
 E'## Services for companies in Abidjan\n\n- Company formation in Côte d''Ivoire (OHADA SA, SARL, SAS)\n- OHADA and Ivorian law compliance\n- M&A and joint-ventures\n- Commercial and distribution contracts\n- Litigation and CCJA arbitration\n\n## Abidjan, West Africa''s economic hub\n\nAbidjan hosts the regional headquarters of international groups in the UEMOA zone. Our French-Ivorian expertise facilitates your investments and operations.',
 2),

('avocat-ohada-cote-divoire', 'Abidjan', 'Côte d''Ivoire', 'CI', 'droit-ohada',
 'Avocat OHADA en Côte d''Ivoire | Cabinet Manuela DIABATE',
 'OHADA Lawyer in Côte d''Ivoire | Manuela DIABATE Law Firm',
 'Avocat spécialiste du droit OHADA en Côte d''Ivoire : sociétés, sûretés, recouvrement, arbitrage CCJA. Cabinet Manuela DIABATE.',
 'OHADA law specialist in Côte d''Ivoire: companies, securities, debt recovery, CCJA arbitration. Manuela DIABATE Law Firm.',
 'Avocat OHADA en Côte d''Ivoire',
 'OHADA Lawyer in Côte d''Ivoire',
 'Expertise complète en droit OHADA pour les entreprises actives en Côte d''Ivoire et dans les 16 autres États membres : actes uniformes, contentieux, arbitrage CCJA.',
 'Full OHADA law expertise for companies operating in Côte d''Ivoire and the 16 other member states: uniform acts, litigation, CCJA arbitration.',
 E'## Notre expertise OHADA\n\n- Acte uniforme sur les sociétés commerciales et le GIE\n- Sûretés et garanties\n- Procédures collectives d''apurement du passif\n- Voies d''exécution et recouvrement\n- Arbitrage CCJA et médiation\n\n## Pourquoi le droit OHADA ?\n\nLe droit OHADA harmonise le droit des affaires dans 17 États africains. Une expertise indispensable pour sécuriser vos opérations en Côte d''Ivoire et au-delà.',
 E'## Our OHADA expertise\n\n- Uniform Act on commercial companies\n- Securities and guarantees\n- Collective insolvency proceedings\n- Enforcement and debt recovery\n- CCJA arbitration and mediation\n\n## Why OHADA law?\n\nOHADA law harmonizes business law across 17 African states — essential to secure your operations in Côte d''Ivoire and beyond.',
 3),

('avocat-droit-etrangers-france', 'Paris', 'France', 'FR', 'droit-des-etrangers',
 'Avocat Droit des Étrangers en France | Cabinet Manuela DIABATE',
 'Immigration Lawyer in France | Manuela DIABATE Law Firm',
 'Avocat en droit des étrangers à Paris : titres de séjour, naturalisation, regroupement familial, OQTF, asile. Cabinet Manuela DIABATE.',
 'Immigration lawyer in Paris: residence permits, naturalization, family reunification, OQTF, asylum. Manuela DIABATE Law Firm.',
 'Avocat en droit des étrangers en France',
 'Immigration Attorney in France',
 'Accompagnement complet en droit des étrangers : démarches préfectorales, contentieux, recours devant les tribunaux administratifs et la CNDA.',
 'Comprehensive immigration law support: prefecture procedures, litigation, appeals before administrative courts and the CNDA.',
 E'## Nos services en droit des étrangers\n\n- Visas et titres de séjour (talent, salarié, vie privée et familiale, étudiant)\n- Naturalisation française\n- Regroupement familial\n- Recours contre OQTF et refus de séjour\n- Demande d''asile et recours CNDA\n\n## Une approche bilingue et internationale\n\nNotre cabinet accompagne particuliers et entreprises (mobilité internationale) en français et en anglais, avec une attention particulière aux ressortissants de Côte d''Ivoire et d''Afrique francophone.',
 E'## Our immigration law services\n\n- Visas and residence permits (talent, employee, private life, student)\n- French naturalization\n- Family reunification\n- Appeals against deportation orders\n- Asylum applications and CNDA appeals\n\n## A bilingual and international approach\n\nWe assist individuals and companies (international mobility) in French and English, with special attention to nationals from Côte d''Ivoire and French-speaking Africa.',
 4),

('avocat-immobilier-paris', 'Paris', 'France', 'FR', 'droit-immobilier',
 'Avocat Droit Immobilier à Paris | Cabinet Manuela DIABATE',
 'Real Estate Attorney in Paris | Manuela DIABATE Law Firm',
 'Avocat en droit immobilier à Paris : transactions, baux, copropriété, contentieux locatif et construction. Cabinet Manuela DIABATE.',
 'Real estate attorney in Paris: transactions, leases, co-ownership, rental and construction litigation.',
 'Avocat en droit immobilier à Paris',
 'Real Estate Attorney in Paris',
 'Conseil et contentieux en droit immobilier à Paris pour particuliers, investisseurs et professionnels.',
 'Real estate advisory and litigation in Paris for individuals, investors and professionals.',
 E'## Nos services en droit immobilier\n\n- Acquisitions et ventes immobilières\n- Baux d''habitation et commerciaux\n- Copropriété et syndic\n- Contentieux locatif et expulsions\n- Droit de la construction et VEFA',
 E'## Our real estate services\n\n- Property acquisitions and sales\n- Residential and commercial leases\n- Co-ownership matters\n- Rental disputes and evictions\n- Construction law and off-plan sales',
 5),

('avocat-fiscaliste-paris', 'Paris', 'France', 'FR', 'droit-fiscal',
 'Avocat Fiscaliste à Paris | Cabinet Manuela DIABATE',
 'Tax Attorney in Paris | Manuela DIABATE Law Firm',
 'Avocat fiscaliste à Paris : optimisation fiscale, contrôles, contentieux, fiscalité internationale France-Afrique. Cabinet Manuela DIABATE.',
 'Tax attorney in Paris: tax optimization, audits, litigation, France-Africa international taxation.',
 'Avocat fiscaliste à Paris',
 'Tax Attorney in Paris',
 'Conseil fiscal stratégique pour entreprises et particuliers, fiscalité internationale et contentieux.',
 'Strategic tax advisory for companies and individuals, international taxation and litigation.',
 E'## Nos services en droit fiscal\n\n- Optimisation et stratégie fiscale\n- Contrôles fiscaux et redressements\n- Contentieux fiscal\n- Fiscalité internationale et conventions\n- Prix de transfert et opérations transfrontalières',
 E'## Our tax law services\n\n- Tax strategy and optimization\n- Tax audits and reassessments\n- Tax litigation\n- International taxation and treaties\n- Transfer pricing and cross-border operations',
 6),

('avocat-arbitrage-international-paris', 'Paris', 'France', 'FR', 'arbitrage',
 'Avocat Arbitrage International à Paris | Cabinet Manuela DIABATE',
 'International Arbitration Attorney in Paris | Manuela DIABATE',
 'Avocat en arbitrage international à Paris : CCI, CCJA OHADA, ad hoc. Représentation et conseil franco-africain.',
 'International arbitration attorney in Paris: ICC, OHADA CCJA, ad hoc. French-African representation and counsel.',
 'Avocat en arbitrage international à Paris',
 'International Arbitration Attorney in Paris',
 'Représentation dans les procédures d''arbitrage commercial international, expertise CCI et CCJA OHADA.',
 'Representation in international commercial arbitration proceedings, ICC and OHADA CCJA expertise.',
 E'## Nos services en arbitrage\n\n- Arbitrage CCI (Chambre de Commerce Internationale)\n- Arbitrage CCJA OHADA\n- Arbitrages ad hoc UNCITRAL\n- Médiation commerciale internationale\n- Exécution des sentences arbitrales',
 E'## Our arbitration services\n\n- ICC arbitration\n- OHADA CCJA arbitration\n- UNCITRAL ad hoc arbitration\n- International commercial mediation\n- Enforcement of arbitral awards',
 7),

('avocat-investissements-afrique-france', 'Paris', 'France', 'FR', 'droit-des-affaires',
 'Avocat Investissements Afrique-France | Cabinet Manuela DIABATE',
 'Africa-France Investment Attorney | Manuela DIABATE Law Firm',
 'Accompagnement juridique des investissements entre l''Afrique et la France : structuration, fiscalité, conformité OHADA.',
 'Legal support for investments between Africa and France: structuring, taxation, OHADA compliance.',
 'Avocat investissements Afrique – France',
 'Africa-France Investment Attorney',
 'Cabinet spécialisé dans les flux d''investissements entre la France et l''Afrique francophone : structuration juridique, fiscalité, conformité.',
 'Firm specialized in investment flows between France and French-speaking Africa: legal structuring, taxation, compliance.',
 E'## Notre accompagnement\n\n- Structuration de holdings franco-africaines\n- Joint-ventures et partenariats\n- Investissements directs étrangers en zone OHADA\n- Levées de fonds et financements\n- Conformité réglementaire (anti-blanchiment, sanctions)\n\n## Pourquoi un cabinet franco-africain ?\n\nLes investissements entre la France et l''Afrique exigent une double expertise. Nous offrons un point de contact unique pour vos opérations dans les deux juridictions.',
 E'## Our support\n\n- Franco-African holding structuring\n- Joint-ventures and partnerships\n- Foreign direct investments in OHADA zone\n- Fundraising and financing\n- Regulatory compliance (AML, sanctions)\n\n## Why a French-African firm?\n\nInvestments between France and Africa require dual expertise. We offer a single point of contact for your operations in both jurisdictions.',
 8),

('avocat-penal-paris', 'Paris', 'France', 'FR', 'droit-penal',
 'Avocat Pénal à Paris | Cabinet Manuela DIABATE',
 'Criminal Defense Attorney in Paris | Manuela DIABATE',
 'Avocat pénaliste à Paris : défense, garde à vue, instruction, comparution immédiate, cour d''assises.',
 'Criminal defense attorney in Paris: custody, investigation, immediate appearance, assize court.',
 'Avocat pénaliste à Paris',
 'Criminal Defense Attorney in Paris',
 'Défense pénale en toutes matières : droit commun, affaires, étrangers.',
 'Criminal defense in all matters: common law, business crime, immigration-related.',
 E'## Nos interventions\n\n- Garde à vue et défense pénale d''urgence\n- Instruction et mise en examen\n- Comparution immédiate et correctionnelle\n- Cour d''assises\n- Droit pénal des affaires',
 E'## Our interventions\n\n- Police custody and emergency criminal defense\n- Judicial investigation\n- Immediate appearance and criminal court\n- Assize court\n- Business criminal law',
 9),

('avocat-france-cote-divoire', 'Paris / Abidjan', 'France & Côte d''Ivoire', 'FR', NULL,
 'Avocat France – Côte d''Ivoire | Cabinet Manuela DIABATE',
 'France – Côte d''Ivoire Lawyer | Manuela DIABATE Law Firm',
 'Cabinet d''avocats France – Côte d''Ivoire : affaires, OHADA, immigration, fiscalité, contentieux transfrontalier.',
 'France – Côte d''Ivoire law firm: business, OHADA, immigration, taxation, cross-border litigation.',
 'Cabinet d''avocats France – Côte d''Ivoire',
 'France – Côte d''Ivoire Law Firm',
 'Le pont juridique entre Paris et Abidjan : un cabinet, deux juridictions, une expertise franco-ivoirienne reconnue.',
 'The legal bridge between Paris and Abidjan: one firm, two jurisdictions, recognized French-Ivorian expertise.',
 E'## Pourquoi nous choisir ?\n\n- Expertise simultanée du droit français et du droit OHADA / ivoirien\n- Équipe bilingue français / anglais\n- Réseau de correspondants en Côte d''Ivoire\n- Accompagnement des particuliers et des entreprises\n\n## Domaines d''intervention\n\n- Droit des affaires & M&A transfrontaliers\n- Investissements et joint-ventures\n- Immigration et mobilité internationale\n- Fiscalité internationale\n- Arbitrage et contentieux',
 E'## Why choose us?\n\n- Combined expertise in French and OHADA / Ivorian law\n- Bilingual French / English team\n- Network of correspondents in Côte d''Ivoire\n- Support for individuals and companies\n\n## Practice areas\n\n- Cross-border business law and M&A\n- Investments and joint-ventures\n- Immigration and international mobility\n- International taxation\n- Arbitration and litigation',
 10),

('avocat-recouvrement-creances-abidjan', 'Abidjan', 'Côte d''Ivoire', 'CI', 'droit-des-affaires',
 'Avocat Recouvrement de Créances à Abidjan | Manuela DIABATE',
 'Debt Recovery Attorney in Abidjan | Manuela DIABATE',
 'Recouvrement amiable et judiciaire de créances en Côte d''Ivoire selon le droit OHADA. Cabinet Manuela DIABATE.',
 'Amicable and judicial debt recovery in Côte d''Ivoire under OHADA law.',
 'Avocat recouvrement de créances à Abidjan',
 'Debt Recovery Attorney in Abidjan',
 'Procédures simplifiées et voies d''exécution OHADA pour récupérer vos créances en Côte d''Ivoire.',
 'OHADA simplified procedures and enforcement to recover your claims in Côte d''Ivoire.',
 E'## Nos services\n\n- Mise en demeure et négociation amiable\n- Procédure d''injonction de payer (OHADA)\n- Saisies et voies d''exécution\n- Procédures collectives\n- Recouvrement transfrontalier France – Afrique',
 E'## Our services\n\n- Formal notice and amicable negotiation\n- OHADA injunction to pay procedure\n- Seizures and enforcement\n- Insolvency proceedings\n- France-Africa cross-border recovery',
 11),

('avocat-creation-entreprise-cote-divoire', 'Abidjan', 'Côte d''Ivoire', 'CI', 'droit-des-affaires',
 'Création d''Entreprise en Côte d''Ivoire — Avocat | Manuela DIABATE',
 'Company Formation in Côte d''Ivoire — Attorney | Manuela DIABATE',
 'Avocat pour la création d''entreprise en Côte d''Ivoire : SA, SARL, SAS OHADA, immatriculation CEPICI.',
 'Attorney for company formation in Côte d''Ivoire: OHADA SA, SARL, SAS, CEPICI registration.',
 'Création d''entreprise en Côte d''Ivoire',
 'Company Formation in Côte d''Ivoire',
 'Accompagnement complet pour créer votre société en Côte d''Ivoire : choix de la forme, statuts, immatriculation, conformité.',
 'Complete support to set up your company in Côte d''Ivoire: form selection, articles, registration, compliance.',
 E'## Étapes de création\n\n1. Choix de la forme sociale (SA, SARL, SAS OHADA, succursale)\n2. Rédaction des statuts conformes à l''Acte uniforme OHADA\n3. Immatriculation au CEPICI (guichet unique)\n4. Ouverture de comptes bancaires\n5. Conformité fiscale et sociale\n\n## Pour qui ?\n\nInvestisseurs étrangers, groupes français souhaitant s''implanter en Afrique de l''Ouest, entrepreneurs ivoiriens.',
 E'## Formation steps\n\n1. Choice of legal form (OHADA SA, SARL, SAS, branch)\n2. Drafting of OHADA-compliant articles\n3. Registration with CEPICI (one-stop shop)\n4. Bank account opening\n5. Tax and social compliance\n\n## For whom?\n\nForeign investors, French groups expanding into West Africa, Ivorian entrepreneurs.',
 12) ON CONFLICT (slug) DO NOTHING;
