// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jnrhhnqqtwmnsfoljirw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpucmhobnFxdHdtbnNmb2xqaXJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODUxNjE4NTgsImV4cCI6MjEwMDczNzg1OH0.sn1NYKoGiFZ6L5keMkx-hk86pPKu4zmjoYSRfl1L4so";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});